language: rust
rust:
    - nightly
    - beta
sudo: false
before_script:
    - git clone --depth 1 https://github.com/huonw/travis-cargo
      # make a short alias (`alias` itself doesn't work)
    - ln -s ./travis-cargo/travis-cargo.py tc
script:
    - ./tc cargo build
    - ./tc cargo test
    - ./tc cargo bench
    - ./tc cargo doc
after_success:
    - git config user.name "Travis-CI Doc Bot"
    - git config user.email "willusher.life@gmail.com"
      # upload the documentation from the build with beta (automatically only actually
      # runs on the master branch)
    - ./tc --only beta doc-upload
env:
    global:
        secure: dtn9JgG7d2pFG/Y429JmXx4N8XsU5G6EQ7Jg2yQF6Xzq7m0jCReDVPjsIcukJqyHWiXAUUVKOpe2G86u9BRQbT6b/lPeCQxZRrEwtM1rJRqfrEJd1s4n1g7kK9H0u86IlvMXA5qEmPvyj5AcmTb+wPL4gqRxCl+hSEcSuPp7/ZQ=

